<a href="https://colab.research.google.com/github/MBR4V0/Python/blob/main/Teste_Radm_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive

In [10]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import os

In [ ]:
"Aqui pode-se consultar as pastas que tem no arquivo DRIVE"
os.listdir('/content/drive/MyDrive')

In [16]:
os.listdir('/content/drive/MyDrive/Dados_teste')

['dados.xlsx']

**Etapa 9 — Instalar/importar o Pandas**

In [17]:
import pandas as pd

In [18]:
df = pd.read_excel(
    '/content/drive/MyDrive/Dados_teste/dados.xlsx'
)

In [19]:
df.head()

   Idade  Tumor_cm  Linfonodos  Ki67  TN
0     45       2.1           3    70   1
1     62       1.2           0    15   0
2     51       3.4           5    80   1
3     39       1.5           1    25   0
4     58       2.8           4    65   1

E se você quiser trabalhar com um Excel que está no seu computador?

In [23]:
"from google.colab import files"

"arquivo = files.upload()"

'arquivo = files.upload()'

In [24]:
df.head()

   Idade  Tumor_cm  Linfonodos  Ki67  TN
0     45       2.1           3    70   1
1     62       1.2           0    15   0
2     51       3.4           5    80   1
3     39       1.5           1    25   0
4     58       2.8           4    65   1

In [25]:
df.shape

(8, 5)

**Random Forest**

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [27]:
X = df[['Idade', 'Tumor_cm', 'Linfonodos', 'Ki67']]

In [28]:
y = df['TN']

In [29]:
print("X:")
display(X)

print("y:")
display(y)

X:

   Idade  Tumor_cm  Linfonodos  Ki67
0     45       2.1           3    70
1     62       1.2           0    15
2     51       3.4           5    80
3     39       1.5           1    25
4     58       2.8           4    65
5     67       1.1           0    10
6     43       2.9           3    75
7     55       1.8           1    30

y:

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
Name: TN, dtype: int64

**Separar treinamento e teste (70% dos dados para ensinar o modelo e 30% para testar.)**

In [31]:
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

In [32]:
print("Treinamento:", len(X_treino))
print("Teste:", len(X_teste))

Treinamento: 5
Teste: 3

**Criar o Random Forest**

In [33]:
modelo_rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [34]:
n_estimators=100

**Treinar**

In [38]:
modelo_rf.fit(
    X_treino,
    y_treino
)

RandomForestClassifier(random_state=42)

**Fazer as previsões**

In [39]:
previsao_rf = modelo_rf.predict(
    X_teste
)

**Comparar previsão com realidade**

In [40]:
print("Real:")
print(y_teste.values)

print()

print("Previsão:")
print(previsao_rf)

Real:
[0 0 1]

Previsão:
[0 0 1]

**Calcular a acurácia**

In [41]:
acuracia_rf = accuracy_score(
    y_teste,
    previsao_rf
)

In [43]:
print(
    f"Acurácia Random Forest: {acuracia_rf:.2%}"
)

Acurácia Random Forest: 100.00%