<a href="https://colab.research.google.com/github/MBR4V0/Python/blob/main/Teste2_XGBost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import drive

In [7]:
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import os

In [ ]:
"Aqui pode-se consultar as pastas que tem no arquivo DRIVE"
os.listdir('/content/drive/MyDrive')

In [10]:
os.listdir('/content/drive/MyDrive/Dados_teste')

['dados.xlsx']

**Etapa 9 — Instalar/importar o Pandas**

In [11]:
import pandas as pd

In [12]:
df = pd.read_excel(
    '/content/drive/MyDrive/Dados_teste/dados.xlsx'
)

In [13]:
df.head()

   Idade  Tumor_cm  Linfonodos  Ki67  TN
0     45       2.1           3    70   1
1     62       1.2           0    15   0
2     51       3.4           5    80   1
3     39       1.5           1    25   0
4     58       2.8           4    65   1

E se você quiser trabalhar com um Excel que está no seu computador?

In [14]:
"from google.colab import files"

"arquivo = files.upload()"

'arquivo = files.upload()'

In [15]:
df.head()

   Idade  Tumor_cm  Linfonodos  Ki67  TN
0     45       2.1           3    70   1
1     62       1.2           0    15   0
2     51       3.4           5    80   1
3     39       1.5           1    25   0
4     58       2.8           4    65   1

In [16]:
df.shape

(8, 5)

**Random Forest**

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [18]:
X = df[['Idade', 'Tumor_cm', 'Linfonodos', 'Ki67']]

In [19]:
y = df['TN']

In [20]:
print("X:")
display(X)

print("y:")
display(y)

X:

   Idade  Tumor_cm  Linfonodos  Ki67
0     45       2.1           3    70
1     62       1.2           0    15
2     51       3.4           5    80
3     39       1.5           1    25
4     58       2.8           4    65
5     67       1.1           0    10
6     43       2.9           3    75
7     55       1.8           1    30

y:

0    1
1    0
2    1
3    0
4    1
5    0
6    1
7    0
Name: TN, dtype: int64

**Separar treinamento e teste (70% dos dados para ensinar o modelo e 30% para testar.)**

In [21]:
X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42
)

In [22]:
print("Treinamento:", len(X_treino))
print("Teste:", len(X_teste))

Treinamento: 5
Teste: 3

**Criar o XGBost**

In [23]:
!pip install -q xgboost

In [24]:
from xgboost import XGBClassifier

In [25]:
modelo_xgb = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.1,
    random_state=42
)

In [42]:
modelo_xgb.fit(
    X_treino,
    y_treino
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

**Fazendo as previsões**

In [43]:
previsao_rf = modelo_xgb.predict(
    X_teste
)

In [46]:
previsao_xgb = modelo_xgb.predict(X_teste)

In [47]:
print("Real:")
print(y_teste.values)

print()

print("Previsão:")
print(previsao_rf)

Real:
[0 0 1]

Previsão:
[1 1 1]

In [48]:
acuracia_xgb = accuracy_score(
    y_teste,
    previsao_xgb
)

In [49]:
print(
    f"Acurácia XGBoost: {acuracia_xgb:.2%}"
)

Acurácia XGBoost: 33.33%